print("               _                           ")
print("              | |                          ")
print(" __      _____| | ___ ___  _ __ ___   ___  ")
print(" \ \ /\ / / _ \ |/ __/ _ \| '_ ` _ \ / _ \ " )
print('  \ V  V /  __/ | (_| (_) | | | | | |  __/ ')
print("   \_/\_/ \___|_|\___\___/|_| |_| |_|\___| ")
print("                           coded by SOJAN" )
print("Git hub: https://github.com/SOJAN-HACKER" )
print("  ")
z = input("whats  is your name :")
print("calculator[Addition only now.next coming soon]")
a = input("Enter first number :")
b = input("Enter second number :")
print("  ")
print("Hai "+ z + " your answer is :")
sum =int(a) + int(b)
print(str(sum))
print("Thanku for useing me")
print("  ")
print("Have a nicec day " + str(z))
